# Generated by Django 3.2.15 on 2022-09-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField()),
                ('book_name', models.CharField(max_length=100)),
                ('book_author', models.CharField(max_length=100)),
                ('book_publication', models.CharField(max_length=100)),
                ('book_isbn', models.PositiveIntegerField(unique=True)),
                ('book_category', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Books_Master',
            },
        ),
    ]
