# Generated by Django 3.2.15 on 2022-09-13 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0002_rename_library_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_id',
        ),
    ]
